### PR TITLE
Fix update doi for geolocation point error

### LINKED ISSUE #87: Update DOI function throws an error when geoLocationPoint data is present
### Descriptive summary

When I try to mint or update a DOI record on an object with geoLocationPoint data, I get the following error:

Error updating DOI: error: bad request - datacite: metadata validation error: Element '{http://datacite.org/schema/kernel-4}geoLocationPoint': Character content other than whitespace is not allowed because the content type is 'element-only'., line 47

For example, https://library.ucsd.edu/dc/object/bb6930466p has point data and an existing DOI. When pushing the Update DOI Record button, I get the error above. Note that the EZID record, https://ezid.cdlib.org/id/doi:10.6075/J01V5BW2, currently has the point data because it was manually entered at the time of the original minting. I can't seem to update it now.

### Related work

https://github.com/ucsdlib/damsrepo/issues/74.

### PR DESCRIPTION
**Pull request by VivianChu**
Fixes #87 

Update datacite.xsl to fix geolocation point issue

Here are some screen shots.
Before the fix - error

beforeFixGeoPointError

After the fix

afterFixGeoPoint
ezid

@ucsdlib/developers - Please review.  Thanks

### CODE REVIEW

**Review by lsitu — APPROVED** [review]
@VivianChu It looks good. Thanks.

**Comment by gamontoya** [comment]
@VivianChu Should this be closed?

**Comment by VivianChu** [comment]
@gamontoya - yes this should be closed since it got deployed to production. I’ll close it.

**Comment by VivianChu** [comment]
@gamontoya - this is a pull request. I think it should be automatically closed when the change is merged. I don’t see close button.

**Comment by gamontoya** [comment]
@VivianChu Yes, that's odd that there is no close button. @mcritchlow As admin can you close this?

**Comment by mcritchlow** [comment]
Since this is a pull request that's already merged, there's nothing to close. It's as 'closed' as it can get :)

**Pull request merged**
