### PR TITLE
Refactor the FileStoreServlet codes for error handling. DAMSKEY-582

### PR DESCRIPTION
**Pull request by lsitu**
https://lib-jira.ucsd.edu:8443/browse/DAMSKEY-582

### CODE REVIEW

**Comment by mcritchlow** [comment]
This looks great 👍 . Would you mind taking a pass through the other api classes as well? 

This, for example, seems like something we'd want flagged as an error: https://github.com/ucsdlib/damsrepo/blob/develop/src/java/edu/ucsd/library/dams/api/DAMSAPIServlet.java#L528

**Comment by lsitu** [comment]
Sure. I'll look into dams api to catch them.

**Comment by lsitu** [comment]
@mcritchlow I've corrected those warning and info to error in dams api for loggings. See commit https://github.com/ucsdlib/damsrepo/pull/42/commits/43475f4ac471061a04975fc7a69dc2386bf0ddd3

**Comment by mcritchlow** [comment]
👍

**Pull request merged**
