### PR TITLE
Add more predicates for subject.

### PR DESCRIPTION
**Pull request by VivianChu**

### CODE REVIEW

**Comment by mcritchlow** [comment]
looks good to me. @lsitu can you take a look when you get a chance please?

**Comment by lsitu** [comment]
@mcritchlow @VivianChu I think these predicates are redundant. They were loaded into the triplestores already, and we can load them into dams-vagran from file https://github.com/ucsdlib/damsrepo/blob/develop/src/sample/predicates/subjectLithologySeriesEtc.nt when running vagran up, which follows Esme's recommendation for adding new predicates into damsrepo.

**Comment by VivianChu** [comment]
@lsitu I didn't know that those predicates already loaded.  I will just do vagrant up now.  Thanks

**Comment by mcritchlow** [comment]
@VivianChu @lsitu thanks everyone!

**Pull request closed without merging**
