### PR TITLE
Upgrade to Tika 1.20 to fix the PDF full text extraction errors

### LINKED ISSUE #82: PDF/Tika full text extraction errors
During VRR testing, @mdpeters has noticed several objects with PDF/document files attached that are failing when Tika is trying to do full text extraction. 

We need to determine whether this can be solved by a newer version of FITS/Tika or?

Example: https://notch8.slack.com/files/U045L1LF7/FGSGWKKHV/-.html

```
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650]   [1m[35mSQL (0.7ms)[0m  UPDATE "users" SET "work_authorizations_count" = COALESCE("work_authorizations_count", 0) + 1 WHERE "users"."id" = $1  [["id", 184]]
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650]   [1m[36m (2.4ms)[0m  [1mCOMMIT[0m
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650]   [1m[35m (0.5ms)[0m  BEGIN
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650]   [1m[36m (0.5ms)[0m  [1mCOMMIT[0m
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650]   [1m[35m (0.5ms)[0m  BEGIN
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650]   [1m[36mSQL (0.5ms)[0m  [1mUPDATE "work_authorizations" SET "updated_at" = '2019-02-25 19:13:32.655751' WHERE "work_authorizations"."id" = $1[0m  [["id", 19]]
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650]   [1m[35m (1.6ms)[0m  COMMIT
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream profile bb5157099g/rightsMetadata (27.0ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream content bb5157099g/rightsMetadata (51.8ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream profile bb5157099g/damsMetadata (25.4ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream profile bb5157099g/DC (25.4ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream content bb5157099g/DC (23.9ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream profile bb5157099g/_rdf.xml (24.8ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream content bb5157099g/_rdf.xml (51.6ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream profile bb5157099g/_4.jpg (23.3ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream content bb5157099g/_4.jpg (24.8ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream profile bb5157099g/_3.jpg (25.2ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream content bb5157099g/_3.jpg (25.9ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream profile bb5157099g/_2.zip (27.4ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream content bb5157099g/_2.zip (3096.9ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream profile bb5157099g/_7.jpg (29.5ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream content bb5157099g/_7.jpg (111.6ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream profile bb5157099g/_5.jpg (29.6ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream content bb5157099g/_5.jpg (43.5ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream profile bb5157099g/_6.jpg (26.1ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream content bb5157099g/_6.jpg (76.3ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream profile bb5157099g/_1.pdf (26.4ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream content bb5157099g/_1.pdf (103.5ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] Loaded datastream profile bb5157099g/fulltext_1.pdf (24.8ms)
App 9538 output: [librarytest] [397cd053-8c86-48c7-8c19-7d0f947c9650] <html><head><title>Apache Tomcat/7.0.40 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 500 - Servlet execution threw an exception</h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u>Servlet execution threw an exception</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>javax.servlet.ServletException: Servlet execution threw an exception
App 9538 output: </pre></p><p><b>root cause</b> <pre>java.lang.NoSuchMethodError: org.apache.pdfbox.pdmodel.PDPage.clear()V
App 9538 output: 	org.apache.tika.parser.pdf.PDF2XHTML.endPage(PDF2XHTML.java:309)
App 9538 output: 	org.apache.pdfbox.util.PDFTextStripper.processPage(PDFTextStripper.java:457)
App 9538 output: 	org.apache.pdfbox.util.PDFTextStripper.processPages(PDFTextStripper.java:379)
App 9538 output: 	org.apache.pdfbox.util.PDFTextStripper.writeText(PDFTextStripper.java:335)
App 9538 output: 	org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:148)
App 9538 output: 	org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:148)
App 9538 output: 	org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
App 9538 output: 	org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
App 9538 output: 	org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120)
App 9538 output: 	edu.ucsd.library.dams.api.DAMSAPIServlet.extractText(DAMSAPIServlet.java:2933)
App 9538 output: 	edu.ucsd.library.dams.api.FedoraAPIServlet.doGet(FedoraAPIServlet.java:343)
App 9538 output: 	javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
App 9538 output: 	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
App 9538 output: </pre></p><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/7.0.40 logs.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.40</h3></body></html>
App 9538 output:   [1m[36m (0.8ms)[0m  [1mBEGIN[0m
App 9538 output:   [1m[35mSQL (0.7ms)[0m  UPDATE "work_authorizations" SET "error" = $1, "updated_at" = $2 WHERE "work_authorizations"."id" = $3  [["error", "See logger for details"], ["updated_at", "2019-02-25 19:13:37.400853"], ["id", 19]]
App 9538 output:   [1m[36m (2.0ms)[0m  [1mCOMMIT[0m
App 9538 output: {"method":"GET","path":"/dc/aeon/requests/32455/set_to_active","format":"html","controller":"Aeon::RequestsController","action":"set_to_active","status":302,"duration":7106.01,"view":0.0,"db":14.65,"location":"https://librarytest.ucsd.edu/dc/aeon/queues/70","@timestamp":"2019-02-25T19:13:37.409Z","@version":"1","message":"[302] GET /dc/aeon/requests/32455/set_to_active (Aeon::RequestsController#set_to_active)"}
```

### PR DESCRIPTION
**Pull request by lsitu**
Fixes #82

Upgrade to Tika 1.20 to fix the PDF full text extraction errors.

@mcritchlow / @ucsdlib/developers Please review and comments

### CODE REVIEW

**Comment by mcritchlow** [comment]
@lsitu - were you able to confirm this fixes the processing errors for the PDFs @mdpeters referenced? If so, this is great :+1:

**Comment by lsitu** [comment]
@mcritchlow I just deployed to to staging and see different errors in QA.Please hold on it and I'll take a look:
```
java.lang.NoSuchFieldError: CONTENT_TYPE_OVERRIDE
	org.apache.tika.detect.OverrideDetector.detect(OverrideDetector.java:34)
	org.apache.tika.detect.CompositeDetector.detect(CompositeDetector.java:77)
	org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:112)
	edu.ucsd.library.dams.api.DAMSAPIServlet.extractText(DAMSAPIServlet.java:2933)
	edu.ucsd.library.dams.api.FedoraAPIServlet.doGet(FedoraAPIServlet.java:343)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
```

**Comment by lsitu** [comment]
@rstanonik I just deployed damsrepo to QA through the jenkins plan. It looks like that the deployment is not clean and I see the old jars of the older version there in `webapp/dams/WEB-INF/lib`. Do we need to delete the existing `webapp/dams` folder from Tomcat before we run the jenkins plan?

**Comment by rstanonik** [comment]
@lsitu It looks to me as if the jars in lib in QA match the jars  in the feature/tika_1.20_upgrade branch.

Any chance you need to update the jars in the feature/tika_1.20_upgrade branch?

Here is how I compared them.

On lib-hydratail-qa

cd /tmp
git clone https://github.com/ucsdlib/damsrepo.git
cd damsrepo
git checkout feature/tika_1.20_upgrade
cd src
mkdir arf
cd arf
cp -rl ../lib/* .
cp -rl ../lib1/* .
diff -r . /usr/local/tomcat/webapps/dams/WEB-INF/lib
There was no difference.

**Comment by lsitu** [comment]
@rstanonik I think it looks good now and I don't see the stale jars in /usr/local/tomcat/webapps/dams/WEB-INF/lib. I don't see the PDF error in QA now. So we just need to make sure the stale jars are gone while moving forward to staging and prod.
For the jars, I may need to add a new dependency jar ( Apache commons-collections 4.0) since I am seeing a problem with a .zip file full text extraction, though we don't need to extract text from .zip files:
```
java.lang.NoClassDefFoundError: org/apache/commons/collections4/IteratorUtils
	org.apache.poi.openxml4j.util.ZipFileZipEntrySource.getEntry(ZipFileZipEntrySource.java:79)
	org.apache.poi.openxml4j.opc.ZipPackage.getPartsImpl(ZipPackage.java:251)
	org.apache.poi.openxml4j.opc.OPCPackage.getParts(OPCPackage.java:721)
	org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:198)
	org.apache.tika.parser.pkg.ZipContainerDetector.detectOPCBased(ZipContainerDetector.java:253)
	org.apache.tika.parser.pkg.ZipContainerDetector.detectZipFormat(ZipContainerDetector.java:173)
	org.apache.tika.parser.pkg.ZipContainerDetector.detect(ZipContainerDetector.java:110)
	org.apache.tika.detect.CompositeDetector.detect(CompositeDetector.java:84)
	org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:116)
	edu.ucsd.library.dams.api.DAMSAPIServlet.extractText(DAMSAPIServlet.java:2933)
	edu.ucsd.library.dams.api.FedoraAPIServlet.doGet(FedoraAPIServlet.java:343)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
``` 
But we don't need to remove the /dams folder with new jars added. Thanks.

**Comment by lsitu** [comment]
@mcritchlow I don't see any errors on QA with the PDF [object bb5157099g ](http://lib-hydratail-qa.ucsd.edu:8080/dams/fedora/objects/bb5157099g/datastreams/fulltext_1.pdf/content) and the [zip file](http://lib-hydratail-staging.ucsd.edu:8080/dams/fedora/objects/bb82962678/datastreams/fulltext_2.zip/content) now. So I think we are ready to merge the PR and deploy it to staging so that @mdpeters can test it there. Thanks.

**Comment by mcritchlow** [comment]
@lsitu that's great!

**Pull request merged**
